### ISSUE TITLE
Don't works with mongoid on Rails 4.2.3

### ISSUE THREAD

**Issue by kevin-jj** [charlotte-ruby/impressionist#195]
```ruby
Impressionist.setup do |config|
  # Define ORM. Could be :active_record (default), :mongo_mapper or :mongoid
  config.orm = :mongoid #:active_record
end
```

Exception:
```ruby
NoMethodError - undefined method `is_impressionable' for #<Class:0x007f9578204468>:
  activerecord (4.2.3) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
```
