### ISSUE TITLE
Impressionist doesn't work with sitemap_notifier

### ISSUE THREAD

**Issue by bcackerman** [charlotte-ruby/impressionist#65]
Using the latest version of impressionist `gem 'impressionist', '~> 1.2.0'`, it will not work with `sitemap_notifier` version `1.0.0`.  The error received is 

.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.11/lib/active_record/dynamic_matchers.rb:55:in `method_missing': undefined local variable or method`is_impressionable' for #Class:0x007f8902c8e690 (NameError)
